// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fgzlliwadflsvsmvynuq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZnemxsaXdhZGZsc3ZzbXZ5bnVxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2Nzk1NTMsImV4cCI6MjA3NDI1NTU1M30.gB8GNenMMgXZXk3hMfO-eBhmYHtQKFwoKcLq9ohwvgo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});